#!/bin/sh

# Default options
OPTS_MAKEFILE="`find . -maxdepth 1 -name [Mm]akefile`"
OPTS_DRYRUN=false
OPTS_KEEPGOING=false
OPTS_TARGETS=""

DEBUG=false

# Show usage
usage () {
    cat <<EOL
Usage: `basename $0` [-f makefile] [-hkn] [target]
Options:
    -f FILE       Read FILE as a makefile
    -h            Print this message and exit.
    -k            Keep going when some targets can't be made.
    -n            Don't actually run any commands; just print them
    -v            Verbose mode
EOL
}

# Log functions
log () {
    if [ -z $2 ]; then
        LOC=$(basename $0)
    else
        LOC=$2
    fi

    echo "$LOC: $1"
}
error () { log "*** $1" $2 >&2; }
fatal () { error "$1  Stop" $2; }

# Debug functions
DEBUG_INDENT=""
debug () { $DEBUG && echo '\033[90m'"${DEBUG_INDENT}$1"'\033[0m'; }
indent_debug () { DEBUG_INDENT="${DEBUG_INDENT}  "; }
shift_debug () { DEBUG_INDENT=`echo "$DEBUG_INDENT" | cut -c 3-`; }

# Create tempdir
init_tmpdir () {
    # Uses TMPDIR (fallback: /tmp)
    # ex: /tmp/maque-1234
    TDIR=${TMPDIR:-/tmp/}$(basename $0)-$$
    mkdir -p $TDIR
    trap "rm -r $TDIR" EXIT
}

# Parse commandline options
parse_commandline () {
    args=`getopt "f:hknv" $*`

    if [ $? != 0 ]; then
        usage >&2
        exit 2
    fi

    set -- $args
    for i; do
        case "$i" in
            -h) usage
                exit 0
                shift;;
            -f) OPTS_MAKEFILE=$2
                shift 2;;
            -k) OPTS_KEEPGOING=true
                shift;;
            -n) OPTS_DRYRUN=true
                shift;;
            -v) DEBUG=true
                shift;;
            --) shift
                break;;
        esac
    done

    # Testing makefile existence
    if [ ! -f $OPTS_MAKEFILE ] || [ -z $OPTS_MAKEFILE ]; then
        fatal "Makefile not found."
        exit 2
    fi

    OPTS_TARGETS=$*
}

# Parse makefile
parse_makefile () {
    local CURRENT_TARGET=""
    local DEFAULT_TARGET=""
    local LINE_NB=0
    local LINE

    # Keep leading spaces/tabs in `read`
    local OLDIFS=$IFS
    IFS=''

    while read RAW_LINE; do
        LINE=`echo $RAW_LINE | sed -e 's/#.*$//g' -e 's/[[:space:]]*$//'`
        LINE_NB=$((LINE_NB + 1))
        if [ -z $LINE ]; then
            # Empty line, do nothing
            continue
        elif [ ! -z $CURRENT_TARGET ] && (echo "$LINE" | grep -q "^$(printf '\t')"); then
            # Append commands to $CURRENT_TARGET commands file
            echo "$LINE" | sed 's/^[[:space:]]*\(.*\)$/\1/' >> $TDIR/$CURRENT_TARGET/commands
        elif (echo "$LINE" | grep -q '^.\+:\( .\+\)*$'); then
            # Change $CURRENT_TARGET and add dependencies in file
            CURRENT_TARGET=`echo $LINE | cut -d ':' -f 1`
            mkdir -p $TDIR/$CURRENT_TARGET
            touch $TDIR/$CURRENT_TARGET/commands
            echo "$LINE" | sed 's/^.*: *//g' > $TDIR/$CURRENT_TARGET/dependencies

            if [ -z $DEFAULT_TARGET ]; then
                DEFAULT_TARGET=$CURRENT_TARGET
            fi
        else
            fatal "Error parsing makefile." "$1:$LINE_NB"
            exit 2
        fi
    done < $1

    # Restore IFS
    IFS=$OLDIFS

    # Set default target if no target specified
    if [ -z "$OPTS_TARGETS" ]; then
        OPTS_TARGETS=$DEFAULT_TARGET
    fi
}


# @returns: 0 = nothing done ; 1 = target just built ; 2 = error
build_target_if_needed () {
    local TARGET=$1
    local NEED_BUILD=false
    local NEWER_DEPS

    if [ -d $TDIR/$TARGET ]; then
        # Debugging
        debug "Building target \`$TARGET'"
        indent_debug

        if ! [ -f $TARGET ]; then
            debug "--> File doesn't exists"
            NEED_BUILD=true
        fi

        if [ -s $TDIR/$TARGET/dependencies ]; then
            DEPS=`cat $TDIR/$TARGET/dependencies`
            # `eval` is needed to correctly expand $DEPS as multiple arguments
            eval build_targets $DEPS
            case $? in
                1)  NEED_BUILD=true;;
                2)  shift_debug
                    return 2;; # Deps build failed
            esac

            if ! $NEED_BUILD; then # Target already built ; check if update needed
                NEWER_DEPS=$(eval find $DEPS -newer $TARGET) # `eval` to expand $DEPS
                if [ -n "$NEWER_DEPS" ]; then
                    debug "--> Newer files"
                    NEED_BUILD=true
                fi
            fi
        fi

        shift_debug

        if $NEED_BUILD; then
            debug "Need to build \`$TARGET'"
            run_commands_in_file $TDIR/$TARGET/commands

            if [ $? -eq 1 ]; then
                return 2 # Command failed
            else
                return 1 # We actually did something!
            fi
        else
            debug "Target \`$TARGET' already up to date"
            return 0 # Already up to date
        fi

        return 1 # Target was built
    elif ! [ -f $TARGET ]; then
        if ! [ -z $PARENT_TARGET ]; then
            fatal "No rule to make target \`$TARGET', needed by \`$PARENT_TARGET'."
        else
            fatal "No rule to make target \`$TARGET'."
        fi
        return 2
    else
        return 0 # Can't build but file exists
    fi
}

# Build multiple targets
build_targets () {
    local PARENT_TARGET=$TARGET # Expose parent target
    local TARGET
    local WAS_BUILT=0
    for TARGET; do
        build_target_if_needed $TARGET
        case $? in
            1) WAS_BUILT=1;;
            2) return 2;; # Target errored
        esac
    done

    return $WAS_BUILT
}

# Run commands
run_commands_in_file () {
    local IFS=''
    local RESULT
    while read CMD; do
        echo "$CMD"
        if ! $OPTS_DRYRUN; then
            sh -c "$CMD"
            RESULT=$?
            if [ $RESULT -ne 0 ] && ! $OPTS_KEEPGOING; then
                error "[$TARGET] Error $RESULT"
                return 1
            fi
        fi
    done < $1

    return 0
}

# Run everything
init_tmpdir
parse_commandline $*
parse_makefile "$OPTS_MAKEFILE"
build_targets $OPTS_TARGETS

# vim: ts=4:sw=4:et
